name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: x86_64-unknown-linux-gnu
          - arch: arm64
            platform: aarch64-unknown-linux-gnu

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-4-dev libadwaita-1-dev flatpak flatpak-builder

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.platform }}

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Set up cross-compilation for ARM64
      if: matrix.arch == 'arm64'
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

    - name: Build Flatpak
      run: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install -y flathub org.gnome.Platform//45 org.gnome.Sdk//45 org.freedesktop.Sdk.Extension.rust-stable
        flatpak-builder --repo=repo --force-clean build-dir lol.janjic.puter.yml
        flatpak build-bundle repo puter-${{ matrix.arch }}.flatpak lol.janjic.puter

    - name: Upload Flatpak artifact
      uses: actions/upload-artifact@v4
      with:
        name: puter-${{ matrix.arch }}
        path: puter-${{ matrix.arch }}.flatpak

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          puter-amd64/puter-amd64.flatpak
          puter-arm64/puter-arm64.flatpak
        draft: false
        prerelease: false
        generate_release_notes: true 