name: Build and Deploy Libadwaita GTK4 Rust App for aarch64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for aarch64-unknown-linux-gnu
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install cross-compilation tools
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: aarch64-unknown-linux-gnu
          command: build
          args: --release

      - name: Configure ARM64 repositories
        run: |
          # Add ARM64 architecture
          sudo dpkg --add-architecture arm64
          
          # Configure Ubuntu Ports repositories
          sudo tee /etc/apt/sources.list.d/arm64.list << EOF
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted universe multiverse
          EOF
          
          sudo apt-get update

      - name: Install dependencies
        run: |
          # Install GTK4 and Libadwaita development files
          sudo apt-get install -y \
            pkg-config \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libglib2.0-dev \
            libglib2.0-dev:arm64 \
            libcairo2-dev:arm64 \
            libpango1.0-dev:arm64 \
            libatk1.0-dev:arm64 \
            libgdk-pixbuf2.0-dev:arm64 \
            libgtk-4-dev:arm64 \
            libadwaita-1-dev:arm64 \
            --no-install-recommends

      - name: Configure cross-compilation environment
        run: |
          # Set up pkg-config for cross-compilation
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_SYSROOT_DIR=/usr" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Build project
        env:
          PKG_CONFIG_ALLOW_CROSS: "1"
          PKG_CONFIG_PATH: "/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig"
          PKG_CONFIG_LIBDIR: "/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig"
          PKG_CONFIG_SYSROOT_DIR: "/usr"
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: "aarch64-linux-gnu-gcc"
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: libadwaita-gtk4-app-aarch64-unknown-linux-gnu
          path: target/aarch64-unknown-linux-gnu/release/puter