name: Flatpak Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        mkdir -p /github/home/.local/share/flatpak
        chown -R root:root /github/home/.local/share/flatpak
        export XDG_DATA_HOME=/github/home/.local/share
        flatpak --system remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install SDK
      run: |
        flatpak --system install -y flathub org.gnome.Platform//47
        flatpak --system install -y flathub org.gnome.Sdk//47
        flatpak --system install -y flathub org.freedesktop.Sdk.Extension.rust-stable//23.08

    - name: Build in Flatpak environment
      run: |
        flatpak-builder --user --force-clean build-dir lol.janjic.puter.yml
        flatpak-builder --user --repo=repo --force-clean build-dir lol.janjic.puter.yml
        flatpak build-bundle repo puter-flatpak.flatpak lol.janjic.puter

    - name: Upload Flatpak Bundle
      uses: actions/upload-artifact@v4
      with:
        name: puter-flatpak
        path: puter-flatpak.flatpak 