name: Flatpak Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flatpak:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Flatpak
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
    
    - name: Add Flathub
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    
    - name: Install SDK
      run: |
        sudo flatpak install -y flathub org.gnome.Platform//47
        sudo flatpak install -y flathub org.gnome.Sdk//47
        sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.rust-stable//23.08
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: sudo apt-get install -y gettext
    
    - name: Build project
      run: cargo build --release
    
    - name: Prepare Flatpak files
      run: |
        mkdir -p flatpak-build/bin
        mkdir -p flatpak-build/share/icons/hicolor/scalable/apps
        mkdir -p flatpak-build/share/applications
        mkdir -p flatpak-build/share/metainfo
        mkdir -p flatpak-build/share/locale/sr_RS/LC_MESSAGES
        
        cp target/release/puter flatpak-build/bin/
        cp data/icons/hicolor/scalable/apps/lol.janjic.puter.svg flatpak-build/share/icons/hicolor/scalable/apps/
        cp lol.janjic.puter.desktop flatpak-build/share/applications/
        cp lol.janjic.puter.metainfo.xml flatpak-build/share/metainfo/
        msgfmt -o puter.mo po/sr_RS/LC_MESSAGES/puter.po
        cp puter.mo flatpak-build/share/locale/sr_RS/LC_MESSAGES/
    
    - name: Build Flatpak
      run: |
        flatpak-builder --user --force-clean build-dir lol.janjic.puter.yml
        flatpak-builder --user --repo=repo --force-clean build-dir lol.janjic.puter.yml
        flatpak build-bundle repo puter.flatpak lol.janjic.puter
    
    - name: Upload Flatpak Bundle
      uses: actions/upload-artifact@v4
      with:
        name: puter.flatpak
        path: puter.flatpak 