name: Build and Package Puter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flatpak
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.gnome.Sdk//24.08 org.gnome.Platform//24.08 org.freedesktop.Sdk.Extension.rust-stable//24.08

      - name: Set up Rust
        run: |
          rustup show
          rustc --version
          cargo --version

      - name: Build Rust project
        run: |
          cargo build --release
          mkdir -p flatpak-build/bin
          cp target/release/puter flatpak-build/bin/

      - name: Prepare Flatpak build directory
        run: |
          mkdir -p flatpak-build/share/applications
          mkdir -p flatpak-build/share/icons/hicolor/scalable/apps
          mkdir -p flatpak-build/share/metainfo
          cp lol.janjic.puter.desktop flatpak-build/share/applications/
          cp data/icons/hicolor/scalable/apps/lol.janjic.puter.svg flatpak-build/share/icons/hicolor/scalable/apps/
          cp lol.janjic.puter.metainfo.xml flatpak-build/share/metainfo/

      - name: Build Flatpak package
        run: |
          flatpak-builder --user --force-clean build-dir lol.janjic.puter.yml

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: puter-flatpak
          path: build-dir
