name: Build Libadwaita GTK4 Rust App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libgtk-4-dev \
            libadwaita-1-dev \
            pkg-config \
            gettext \
            gcc-aarch64-linux-gnu \
            libglib2.0-dev \
            libgdk-pixbuf-2.0-dev \
            libcairo2-dev \
            libpango1.0-dev \
            libatk1.0-dev \
            libsoup-3.0-dev \
            libgirepository1.0-dev \
            gir1.2-gtk-4.0 \
            qemu-user-static \
            libgobject-2.0-dev \
            libgio2.0-dev \
            libgmodule-2.0-dev \
            libgthread-2.0-dev

      - name: Configure pkg-config for cross-compilation
        run: |
          echo "export PKG_CONFIG_ALLOW_CROSS=1" >> $HOME/.bashrc
          echo "export PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu" >> $HOME/.bashrc
          echo "export PKG_CONFIG_PATH=/usr/aarch64-linux-gnu/lib/pkgconfig:/usr/aarch64-linux-gnu/share/pkgconfig" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build project
        run: |
          cargo build --release --target=${{ matrix.target }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: libadwaita-gtk4-app-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/*
