name: Build and Deliver Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    strategy:
      matrix:
        arch: [amd64, aarch64]
    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        mkdir -p /github/home/.local/share/flatpak
        chown -R root:root /github/home/.local/share/flatpak
        export XDG_DATA_HOME=/github/home/.local/share
        flatpak --system remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install SDK and Rust Extension
      run: |
        flatpak --system install -y flathub org.gnome.Platform//47
        flatpak --system install -y flathub org.gnome.Sdk//47
        flatpak --system install -y flathub org.freedesktop.Sdk.Extension.rust-stable//23.08

    - name: Build project
      run: |
        mkdir -p /tmp/build/target
        chmod 777 /tmp/build/target
        export CARGO_TARGET_DIR=/tmp/build/target
        flatpak run --command=sh \
          --runtime=org.gnome.Sdk//47 \
          --filesystem=host \
          --share=network \
          --env=PATH=$PATH:/usr/bin:/bin:/usr/lib/sdk/rust-stable/bin \
          --env=CARGO_HOME=/usr/lib/sdk/rust-stable/cargo \
          --env=RUSTUP_HOME=/usr/lib/sdk/rust-stable/rustup \
          --env=CARGO_TARGET_DIR=/tmp/build/target \
          org.gnome.Sdk//47 -c '
            rustc --version &&
            cargo build --release --target ${{ matrix.arch }}-unknown-linux-gnu
          '

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: puter-${{ matrix.arch }}
        path: /tmp/build/target/${{ matrix.arch }}-unknown-linux-gnu/release/puter