name: Build Libadwaita GTK4 Rust App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libgtk-4-dev \
            libadwaita-1-dev \
            pkg-config \
            gettext \
            gcc-aarch64-linux-gnu

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build project
        run: |
          cargo build --release --target=${{ matrix.target }}
