name: Build Libadwaita GTK4 Rust App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest \
            bash -c "apt-get update && \
                     apt-get install -y pkg-config libglib2.0-dev libcairo2-dev libgtk-4-dev libadwaita-1-dev gettext gettext-base && \
                     cargo build --release --target x86_64-unknown-linux-gnu"

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: libadwaita-gtk4-app-x86_64-unknown-linux-gnu
          path: /workspace/target/x86_64-unknown-linux-gnu/release/*
