name: Build and Deliver Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
    - uses: actions/checkout@v4

    - name: Build project
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace rustembedded/cross:${{ matrix.arch }}-unknown-linux-gnu \
          bash -c "apt-get update && \
                   apt-get install -y pkg-config libglib2.0-dev libcairo2-dev libgtk-4-dev libadwaita-1-dev gettext gettext-base && \
                   cargo build --release --target ${{ matrix.arch }}-unknown-linux-gnu"

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: puter-${{ matrix.arch }}
        path: /workspace/target/${{ matrix.arch }}-unknown-linux-gnu/release/puter