name: Build and Deliver Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libglib2.0-dev libcairo2-dev libgtk-4-dev

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup default stable
        rustup target add ${{ matrix.arch }}-unknown-linux-gnu

    - name: Build project
      run: |
        mkdir -p /tmp/build/target
        chmod 777 /tmp/build/target
        export CARGO_TARGET_DIR=/tmp/build/target
        export PKG_CONFIG_ALLOW_CROSS=1
        export PKG_CONFIG_PATH=/usr/lib/${{ matrix.arch }}-linux-gnu/pkgconfig:/usr/share/pkgconfig
        cargo build --release --target ${{ matrix.arch }}-unknown-linux-gnu

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: puter-${{ matrix.arch }}
        path: /tmp/build/target/${{ matrix.arch }}-unknown-linux-gnu/release/puter