name: Build and Deploy Libadwaita GTK4 Rust App for aarch64

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on ARM64
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            build-essential \
            libglib2.0-dev \
            libcairo2-dev \
            libpango1.0-dev \
            libatk1.0-dev \
            libgdk-pixbuf2.0-dev \
            libgtk-4-dev \
            libadwaita-1-dev

      - name: Build project
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: libadwaita-gtk4-app-arm64
          path: target/release/puter